### ISSUE TITLE
Inferior URI Specification results in unknown error (80)

### ISSUE THREAD

**Issue by ptusch** [liberkee/openldapjs#57]
When you connect to your LDAP server without the proper uri prefix (ldap/ldaps) you'll see that you can't connect and LDAP populates the fllowing error:
`80:Indicates an unknown error condition. This is the default value for NDS error codes which do not map to other LDAP error codes.`

This is very poor since having an explicit error would be far better (wrongUriError or whatever)

**Comment by Radu94** [comment]
This is the case for most negative error codes, we could inspect the error code and add another error class, but if i remember it right the issue with this was that we couldn't find any RFC compliant documentation about negative error codes( at best some comments and defines in the C lib header files).

**Comment by ptusch** [comment]
Can't we just try to parse the URL before we pass it to LDAP?
I assume openldap has some kind of check for this and we might be able to verify the URL that way.

If not, we could check it by hand on the JS side when we pass a hostname.
